language: minimal # setting language to C will override cross-compiler and fail

sudo: required

services:
  - docker

jobs:
  include:
    - statge: build docker image
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker build -f openamp-xilinx-dockerfile.yml -t travis-ci-stage-image .
        - docker tag travis-ci-stage-image ${DOCKER_USERNAME}/openamp-xilinx:latest
        - docker push ${DOCKER_USERNAME}/openamp-xilinx:latest
    - stage: test
      script: docker run --rm ${DOCKER_USERNAME}/openamp-xilinx:latest echo "Successfully build docker image."
